// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwwDMX6ck6XDPlPzbkFi-J7LspLfbhzCE',
    appId: '1:715039295106:web:ae089363317ab41742169b',
    messagingSenderId: '715039295106',
    projectId: 'fir-tapday',
    authDomain: 'fir-tapday.firebaseapp.com',
    storageBucket: 'fir-tapday.appspot.com',
    measurementId: 'G-ZZY57L6NZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ7kfXYVVdVEIHwSrssHpCWDdwVF_XUvQ',
    appId: '1:715039295106:android:cb9cb0c36b02329642169b',
    messagingSenderId: '715039295106',
    projectId: 'fir-tapday',
    storageBucket: 'fir-tapday.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ5I3CmYgGmXf4LpUZ0tTlTFicm3mGg3s',
    appId: '1:715039295106:ios:a7919a4be0b1c39842169b',
    messagingSenderId: '715039295106',
    projectId: 'fir-tapday',
    storageBucket: 'fir-tapday.appspot.com',
    iosBundleId: 'com.example.tapdayNotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ5I3CmYgGmXf4LpUZ0tTlTFicm3mGg3s',
    appId: '1:715039295106:ios:0437d02ee0633e5a42169b',
    messagingSenderId: '715039295106',
    projectId: 'fir-tapday',
    storageBucket: 'fir-tapday.appspot.com',
    iosBundleId: 'com.example.tapdayNotifications.RunnerTests',
  );
}
